<keyword>       ::= "Char" | "else" | "Float" | "for" | "if" | "Int"
                  | "ret" | "while" | "Bool" | "String" | "fn" | "foreach"



<string-literal> ::= "\"\""
                  | "\"" s-char-sequence "\""

<s-char-sequence> ::= <s-char>
                  | <s-char-sequence> <s-char>

<s-char>        ::= tout membre du jeu de caractères source, à l’exception
                    du guillemet double ("), de la barre oblique inverse (\)
                    ou du caractère de saut de ligne escape-sequence



<constant>      ::= <decimal-constant>
                  | <floating-constant>
                  | <character-constant>

<decimal-constant> ::= <nonzero-digit>
                  | <decimal-constant> <digit>

<nonzero-digit> ::= "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9"

<floating-constant> ::= <digit-sequence> "." <digit-sequence>

<digit-sequence> ::= <digit>
                  | <digit-sequence> <digit>

<character-constant> ::= "'" <char> "'"

<char>          ::= Tout membre du jeu de caractères source à l’exception du
                    guillemet simple ('), de la barre oblique inverse (\) ou
                    du caractère de saut de ligne escape-sequence

<escape-sequence> ::= "\a" | "\b" | "\f" | "\n" | "\r" | "\t"
                    | "\v" | "\'" | "\"" | "\\"



<identifier>    ::= <nondigit>
                  | <identifier> <nondigit>
                  | <identifier> <digit>

<nondigit>      ::= "_"
                  | "a" | "b" | "c" | "d" | "e" | "f" | "g" | "h" | "i" | "j"
                  | "k" | "l" | "m" | "n" | "o" | "p" | "q" | "r" | "s" | "t"
                  | "u" | "v" | "w" | "x" | "y" | "z"
                  | "A" | "B" | "C" | "D" | "E" | "F" | "G" | "H" | "I" | "J"
                  | "K" | "L" | "M" | "N" | "O" | "P" | "Q" | "R" | "S" | "T"
                  | "U" | "V" | "W" | "X" | "Y" | "Z"

<digit>         ::= "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9"



<punctuator>    ::= "[" | "]" | "(" | ")" | "{" | "}" | "." | "->" | "++"
                  | "--" | "*" | "+" | "-" | "/" | "%" | "<" | ">" | "<="
                  | ">=" | "==" | "!=" | "&&" | "||" | ":" | ";" | ","
                  | "=" | "*=" | "/=" | "%=" | "+=" | "-=" | "#"
